export * from "./Logo" ;
export * from "../secciones/Home";
export * from "../secciones/Contact";
export * from "../secciones/Footer";
export * from "../secciones/Header";
export * from "../secciones/Projects";
export * from "../secciones/Skills";
export * from "./MailchimpForm";
export * from "./Newsletter";
export * from "../helpers/GoToId";
export * from "./Icons";
