name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        VERSION: 1.2.0
        
    steps:
    - name: Revisa el codigo profundamente
      uses: actions/checkout@v3
      with:
        fetch-depyh: 0
        
    - name: Inicio de sesion en Docker
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Contruir Imagen de Docker
      run: docker build -t $DOCKER_USER/my-portfolio:${VERSION} .
        docker build -t $DOCKER_USER/my-portfolio:latest .
      
    - name: Hacer push de la imagen de Docker
      run: docker push $DOCKER_USER/my-portfolio:${VERSION}
        docker push $DOCKER_USER/my-portfolio:latest
    
        
      
    
  
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
